name: Scrape V2Ray Configs

on:
  schedule:
    - cron: '0 */4 * * *' # هر ۴ ساعت یک بار اجرا می‌شود
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run scraper
        env:
          GITLAB_API_TOKEN: ${{ secrets.GITLAB_API_TOKEN }}
          GITLAB_SNIPPET_ID: ${{ secrets.GITLAB_SNIPPET_ID }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python scraper.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update configs.txt"
          file_pattern: configs.txt
